<div align="center">

# PAO25_25_03_Python_Numpy

### 6 de Julio del 2026

<br>

<img src="img/logoitqv1.jpg" width="650">

<br><br>

</div>

# 0.1 PAO25-25 - Numpy

<div align="center">

<img src="img/python_logo.png" width="550">

</div>

<div align="left">

### Eric Campoverde

<a href="https://github.com/EricJordy/MachineLearning_teoria">Repositorio Git</a>

</div>

<hr style="height:3px;border:none;background:#b30000;">


## 1 NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [1]:
#importar libreria
import numpy as np

### 1.1 Performance Sample, NumPy vs Plain Python

In [4]:
my_list = list(range(10000000))   # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]   # Medir el tiempo que tarda Python en multiplicar cada elemento por 2

CPU times: total: 2.12 s
Wall time: 2.15 s


In [5]:
my_arr = np.arange(10000000) # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2   # Medir el tiempo que tarda NumPy en multiplicar todos los elementos por 2

CPU times: total: 46.9 ms
Wall time: 69.9 ms


### 1.2 Formas de crear ndarrays

In [6]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [7]:
# Lista bidimensional con nombres de frutas y verduras.
shopping_list = [
    ['onions', 'carrots', 'celery'],
    ['apples', 'oranges', 'grapes']
]

# Convertir la lista en un Array de NumPy.
array = np.array(shopping_list)

# Mostrar el contenido.
print(array)

# Mostrar el tipo de dato.
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [8]:
print(np.array([100,10,1]))  # array a partir de una lista
print(np.arange(2,10,2.1))   # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [9]:
# Generar arrays con valores fijos

print(np.zeros(2))        # 1D
print(np.ones((4,3)))     # matrix 2x2
print(np.empty((2,2,2)))  # matrix 2x2x2, no inicializados
print(np.full((5,2),2))   # matrix 5x2
print(np.eye(3))          # matrix identity

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 1.3 Obtener información sobre ndarray

In [10]:
# Crear un Array unidimensional.
my_ndarray = np.array([2, 71, 0, 34])

# Mostrar el Array.
print(my_ndarray)

[ 2 71  0 34]


In [11]:
print(my_ndarray.argmax())   # índice del valor más alto
print(np.amax(my_ndarray))   # Obtener el valor máximo del Array

print(my_ndarray.argmin())   # índice del valor más bajo
print(np.amin(my_ndarray))   # Obtener el valor mínimo del Array

print(my_ndarray.nonzero()) # retorna los índices de los elementos distintos a 0

1
71
2
0
(array([0, 1, 3]),)


In [16]:
# Crear un Array tridimensional de tamaño 5x4x2, lleno de numeros 2.
my_ndarray = np.full((5, 4, 2), 7)
print(my_ndarray)

print(my_ndarray.size)    # número de elementos
print(my_ndarray.shape)   # dimensiones
print(my_ndarray.ndim)    # número de dimensiones

[[[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]]
40
(5, 4, 2)
3


In [17]:
my_ndarray = np.array([2,71,0,34])

print(my_ndarray.size)     # número de elementos
print(my_ndarray.shape)    # dimensiones
print(my_ndarray.ndim)     # número de dimensiones

4
(4,)
1


## Redimensionar los datos

In [19]:
my_ndarray = np.array([[0, 71, 21, 19, 213, 412, 111, 98]]) # matrix 1x8
print(my_ndarray)

print(my_ndarray.shape)     # dimensiones
print(my_ndarray.ndim)      # número de dimensiones

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [21]:
new_dims = my_ndarray.reshape(2, 4)   # cambiar las dimensiones a 2x4
print(new_dims)

print(new_dims.ndim)      # número de dimensiones

[[  0  71  21  19]
 [213 412 111  98]]
2


In [22]:
new_dims = my_ndarray.reshape(4, 2) # cambiar las dimensiones a 4x2
print(new_dims)

print(new_dims.ndim)     # número de dimensiones

[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [32]:
x = np.array([100, 10, 1]).reshape(3,1)
print(x.shape)
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [33]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(new_dims.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [35]:
# reducir
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(2,-1))     # el segundo valor se infiere del primero

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


### 1.4 Manipulación de ndarrays

In [36]:
# Cambiar ejes

new_dims = np.arange(16).reshape(8,2)
print(new_dims)
print(new_dims.swapaxes(0,1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [37]:
# Flip
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(np.flip(new_dims, axis = None))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [38]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(array1)

[ 2  9 10 17]


In [39]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]

print(np.hstack((a1,a2)))      # una al lado de la otra
print(np.hstack((a1,a2)).shape)

print(np.vstack((a1,a2)))      # una encima de la otra
print(np.vstack((a1,a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [40]:
array1 = np.array([[2, 4], [6, 8]])
array2 = np.array([[3, 5], [7, 9]])

print(np.concatenate((array1, array2), axis = 0))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [41]:
# dividir un array
array = np.arange(16).reshape(4,4)

print(array)
print(np.array_split(array, 2, axis = 0))    # divide array en 2 partes iguales
print(np.array_split(array, 3))        # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [42]:
# dividir un array
array = np.arange(16).reshape(4,4)

print(array)
print(np.array_split(array, [3], axis = 1)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [43]:
split = np.array_split(array, [3], axis = 1)

print(split[0][3][0])

12


In [46]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0))   # divide array por la fila 1 y 3
print(np.array_split(array, [1, 3], axis = 1))   # divide array por la columna 1 y 3
# axis = n_dimensions- 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

## 2 Índices y slicing
- De manera análoga a índices y slicing para listas

In [47]:
array = np.arange(10, 16)
print(array)

print(array[-1])     # acceso unidimensional
print(array[:-1])    # slice

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [48]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)

print(array[2, 2]) # fila, columna
print(array[3][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [49]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[0,2,4])
print(array[1][2][4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


## NumPy es row major

In [51]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3) # by default, row major

print(row_major)

[[1 2 3]
 [4 5 6]]


In [52]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C')     # by default, row major
print(row_major)

col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F')     # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


## Slice

In [53]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)

print(array)
print(array[1:3, 2::2])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [56]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)

print(array)
print(array[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


### Diferencias entre índices y slicing en listas y ndarrays:
- ¡Retornan una referencia, no una copia!

In [57]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]

my_copy = lista[0:2]    # devuelve una copia
print(my_copy)

my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [59]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5]    # devuelve una referencia

print(array)
print(my_copy)

my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [60]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy() # hay que hacer la copia explicitamente
my_copy[0] = 222

print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


- Permite asignar valores a un corte

In [61]:
array = np.arange(10)
print(array)

print(array[0:3])

array[0:3] =-1
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


- Slicing condicionales (mask)

In [62]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array %2 == 0
print(mask)
print(array[mask])

print(array[array %2 == 0])

array[mask] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [63]:
array = np.arange(-3,4)
print(array)

array[array < 0] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [64]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array % 2 == 0
print(mask)

array_par = array[mask] # devuelve una copia
print(array_par)

array_par[0] =-10
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


- Acceso a múltiples valores con listados de índices

In [66]:
array = np.arange(0,16).reshape(4,4)
print(array)
print(array[[1,2]])     #selecting rows
print(array[:,[1,2]])   #selecting columns

# cross product of indexes
print(array[[1,2],:][:,[1,2]])

print(array[np.ix_([1,2],[1,2])]) # built in ix_

ar = array[[2,3,1]] # slice, copia
print(ar)
ar[0] = 999
print(ar)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[999 999 999 999]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 3 Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [67]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)

lista += [1]
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [68]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int8)
print(array)

array *= 2
print(array)

array += 10
print(array)
print(array.dtype) # check data type of array

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [69]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1- array_2)
print(array_1 * array_2)
print(array_2 / array_1)

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


### 3.1 Broadcasting
Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande -> <a href="https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html">broad-casting</a>


<h3>3.2 Operadores unitarios y binarios</h3>

<div align="center">

<table>
    <thead>
        <tr>
            <th>Tipo</th>
            <th>Operación</th>
            <th>Descripción</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>Unario</td><td>abs</td><td>Valor absoluto de cada elemento</td></tr>
        <tr><td></td><td>sqrt</td><td>Raiz cuadrada de cada elemento</td></tr>
        <tr><td></td><td>exq</td><td>e^x, siendo x cad
elemento</td></tr>
        <tr><td></td><td>log, log10, log2</td><td>Logaritmos en distintas bases de cada elemento</td></tr>
        <tr><td></td><td>sign</td><td>Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo)</td></tr>
        <tr><td></td><td>ceil</td><td>Redondea cada elemento
por arriba</td></tr>
        <tr><td></td><td>floor</td><td>Redondea cada elemento por abajo</td></tr>
        <tr><td></td><td>isnan</td><td>Retorna si cada elemento es Nan</td></tr>
        <tr><td></td><td>cos, sin, tan </td><td>Operaciones
trigonométricas en cada elemento</td></tr>
        <tr><td></td><td>arcos, arcsin, arctan</td><td>Inversas de operaciones trigonométricas en cada elemento</td></tr>
        <tr><td>Binario</td><td>add</td><td>Suma de dos arrays</td></tr>
        <tr><td></td><td>substract</td><td>Resta de dos arrays</td></tr>
        <tr><td></td><td>multiply</td><td>Multiplicación de dos arrays</td></tr>
        <tr><td></td><td>divide</td><td>División de dos arrays</td></tr>
        <tr><td></td><td>maximum, minimum</td><td>Retorna el valor máximo/mínimo de cada pareja de elementos</td></tr>
        <tr><td></td><td>equal, not_equal</td><td>Retorna la comparación (igual o no igual) de cada pareja de elementos</td></tr>
        <tr><td></td><td>greater, greater_equal,
less, less_equal</td><td>Retorna la comparación(>, >=, <, <= respectivamente) de cada pareja de elementos</td></tr>
    </tbody>
</table>

</div>


In [70]:
# ejemplos de operadores
array = np.arange(5)

print(array)
np.sqrt(array)

[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [71]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])

print(array1)
print(array2)

print(np.greater(array1,array2))
print(np.less(array2, array1))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


## 4 Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc

<div align="center">

<table>
    <thead>
        <tr>
            <th>Funciones</th>
            <th>Descripción</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>sum(arr)</td><td>Suma de todos los elementos de arr</td></tr>
        <tr><td>mean(arr)</td><td>Media aritmética de los elementos
de arr</td></tr>
        <tr><td>std(arr)</td><td>Desviación estándar de los
elementos de arr</td></tr>
        <tr><td>cumsum(arr)</td><td>Devuelve array con la suma
acumulada de cada elementos con todos los anteriores</td></tr>
        <tr><td>cumprod(arr)</td><td>Devuelve array con el producto
acumulado de cada elementos con todos los anteriores</td></tr>
        <tr><td>min(arr), max(arr)</td><td>Mínimo y máximo de arr</td></tr>
        <tr><td>any(arr)</td><td>En array de tipo bool, retorna True
si algún elemento es True</td></tr>
        <tr><td>all(arr)</td><td>En array de tipo bool, retorna True
si todos los elementos son True (o <> 0 en valores numéricos)</td></tr>
        <tr><td>unique(arr)</td><td>Devuelve un array con valores
únicos</td></tr>
        <tr><td>in1d(arr1, arr2)</td><td>Devuelve un array con bool
indicando si cada elemento de arr1 está en arr2</td></tr>
        <tr><td>union1d(arr1, arr2)</td><td>Devuelve la unión de ambos arrays</td></tr>
        <tr><td>intersect1d(arr1, arr2)</td><td>Devuelve la intersección de ambos
arrays</td></tr>
    </tbody>
</table>

</div>


In [73]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [75]:
# any vs all
array1 = np.arange(-8,2).reshape(2,5)
print(array1)

print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores <> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [76]:
# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)

print(array1.all(axis=0))
print(array1.all(axis=1))

print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


## 5 Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multiplicación de matrices, cálculo del determinante, factorizaciones…

<div align="center">

<table>
    <thead>
        <tr>
            <th>Función</th>
            <th>Desc</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>dot(mat1, mat2)</td><td>Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas</td></tr>
        <tr><td>matmul(mat1, mat2)</td><td>Devuelve el producto entre dos matrices</td></tr>
        <tr><td>trace(mat1, mat2)</td><td>Suma de las diagonales de ambas matrices</td></tr>
        <tr><td>det(mat)</td><td>Devuelve el determinante de la matriz</td></tr>
        <tr><td>eig(mat)</td><td>Computa los autovalores y
autovectores de la matriz cuadrada mat</td></tr>
        <tr><td>inv(mat)</td><td>Devuelve la inversa de la matriz Computa la factorización QR de mat</td></tr>
        <tr><td>qr(mat)</td><td>Computa la factorización QR de mat</td></tr>
        <tr><td>solve(A, b)</td><td>Resuelve el sistema lineal de ecuaciones Ax = b para b, cuando A es una matriz cuadrada</td></tr>
        <tr><td>transpose(mat)</td><td>Devuelve la transpuesta de la matrix</td></tr>
    </tbody>
</table>

</div>


In [77]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)

print(A)
print(B)

print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [78]:
import numpy.linalg as lg
import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x- 3y-z = 2
# 2x-y +12z = 32
# Ax = b--> resolver para x

a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])
b = np.array([12,2,32])

print(a)
print(b)

x,y,z = lg.solve(a,b)
print(f'x={x} y={y} z={z}')

print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x- 3*y- z, 2))
print(math.isclose(2*x-y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122808 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [80]:
#matriz identidad
I = np.identity(4)
print(I)

A = np.arange(16).reshape(4,4)
print(A)

print(np.matmul(A,I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


## 6 Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [81]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
mask = prices < 1
print(prices[prices < 1])   #slicing condicional

# mask con los elementos menores de 1
mask = np.where(prices < 1, True, False)
print(mask)
print(prices[mask])

prices[mask] = 1.0
print(prices)

print(np.where(prices < 1, 1.0, prices))

[0.99 0.49]
[ True False False False  True]
[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]
[ 1.   14.49 19.99 20.99  1.  ]


In [82]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99,-1.49, 19.99, 20.99,-0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)

clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [83]:
# limpiar NaN (sustitución)
data = [10, 12,-143, np.nan, 1,-3] # np.nan--> NotANumber, elemento especial
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

print(id(data))
print(id(data_clean))

[  10.   12. -143.    0.    1.   -3.]
2341648062848
2341648420176


In [84]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99,-1.49, 19.99, 20.99,-0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)

credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True
print(credits)

print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [85]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)

rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)

daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)

final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


## 7 Números aleatorios
- Python módulo random

In [86]:
import random
print(random.random())       # número entre 0 y 1
print(random.randint(0,5))   # integral entre dos valores
print(random.uniform(0,5))   # real entre dos valores

0.6088809224851942
1
1.7478424769060708


In [87]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)

'Eevee'

### 7.1 NumPy.random
- Generar fácilmente listas con valores aleatorios

In [89]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.32198021418701217
3
[[1 1 2 3]
 [4 3 2 0]]


In [90]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[ 0.1290991  -0.24713629]
 [ 0.8271571  -0.93338413]
 [ 1.23673137  0.17729703]
 [ 1.05025131 -0.75348152]]


In [91]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

3
6.108101448041154
[[5 1]
 [1 1]]


### 7.2 Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [92]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())
print()

for i in range(6):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())
    print(np.random.rand())

0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764


## 8 Escritura y lectura de ndarrays a archivos
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [95]:
# Importar el módulo para trabajar con rutas.
import os

# Crear la ruta donde se guardará el archivo.
ruta = os.path.join("res", "o_values_array.npy")

# Generar un Array de 3 filas y 3 columnas
# con números enteros aleatorios entre 0 y 8.
values = np.random.randint(9, size=(3, 3))

# Guardar el Array en un archivo .npy.
np.save(ruta, values)

# Mostrar el Array generado.
print(values)

[[2 7 0]
 [5 0 0]
 [4 4 3]]


In [96]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[2 7 0]
 [5 0 0]
 [4 4 3]]


In [97]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")

values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz

In [98]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)

print(type(npzfile.files))
print(npzfile.files)

for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
    print(npzfile[key])

<class 'list'>
['arr_0', 'arr_1', 'arr_2']
[[2 4 6]
 [3 3 2]
 [1 5 7]]
[[0 0]
 [1 2]]
[[14 11 11  3]
 [12  1  7  3]
 [11 14 11 13]
 [ 1  9  5  7]]


### 8.0.1 ¿Por qué molestarse con .npy?
- Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
- ¿Para qué escribir los datos de nuevo?

In [99]:
import os

ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()

data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)

# print(data_array)
ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [100]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()

data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)

196 ms ± 9.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [101]:
%%timeit
data = np.load(ruta_npy)

371 μs ± 61.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [102]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")

356 ms ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 8.0.2 velocidad + simplicidad vs memoria
### 8.1 Ejercicios
- Ejercicios para practicar NumPy: <a href="https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb">https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb</a>


### 1. Import the numpy package under the name np

In [103]:
# Importar la librería NumPy utilizando el alias np
import numpy as np

### 2. Print the numpy version and the configuration

In [104]:
# Mostrar la versión instalada de NumPy
print("Versión de NumPy:", np.__version__)

# Mostrar información sobre la configuración de NumPy
np.show_config()

Versión de NumPy: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ericj/anaconda3/Library/include
    lib directory: C:/Users/ericj/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ericj/anaconda3/Library/include
    lib directory: C:/Users/ericj/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
   

### 3. Create a null vector of size 10

In [105]:
# Crear un vector de tamaño 10 lleno de ceros
vector = np.zeros(10)

print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array

In [107]:
# size indica la cantidad de elementos
# itemsize indica cuántos bytes ocupa cada elemento
memoria = arreglo.size * arreglo.itemsize

print("Memoria utilizada:", memoria, "bytes")

Memoria utilizada: 96 bytes


### 5. How to get the documentation of the numpy add function from the command line?

In [108]:
# Mostrar ayuda detallada
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

### 6. Create a null vector of size 10 but the fifth value which is 1

In [109]:
# Crear un vector de 10 ceros
vector = np.zeros(10)

# Las posiciones comienzan desde 0
# Por eso, la quinta posición tiene el índice 4
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [110]:
# arange genera números desde 10 hasta 49
# El valor 50 no se incluye
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector

In [111]:
# Crear un vector de ejemplo
vector = np.arange(10)

print("Vector original:")
print(vector)

# Invertir el orden de los elementos
vector_invertido = vector[::-1]

print("Vector invertido:")
print(vector_invertido)

Vector original:
[0 1 2 3 4 5 6 7 8 9]
Vector invertido:
[9 8 7 6 5 4 3 2 1 0]


### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [112]:
# Crear un vector con valores de 0 a 8
# reshape transforma el vector en una matriz de 3 filas y 3 columnas
matriz = np.arange(9).reshape(3, 3)

print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [113]:
# Crear el arreglo indicado
vector = np.array([1, 2, 0, 0, 4, 0])

# nonzero devuelve los índices de los valores diferentes de cero
indices = np.nonzero(vector)

print("Índices de elementos diferentes de cero:")
print(indices[0])

Índices de elementos diferentes de cero:
[0 1 4]


### 11. Create a 3x3 identity matrix 

In [115]:
# eye crea una matriz identidad
# La diagonal principal contiene unos y el resto ceros
matriz_identidad = np.eye(3)

print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values

In [116]:
# Crear un arreglo de tres dimensiones
# Los valores aleatorios estarán entre 0 y 1
arreglo = np.random.random((3, 3, 3))

print(arreglo)

[[[0.69666493 0.57541371 0.5797214 ]
  [0.0645069  0.17724613 0.34152709]
  [0.60870258 0.19547496 0.12154847]]

 [[0.93467951 0.31097992 0.47431657]
  [0.06221156 0.27534409 0.22598839]
  [0.94305353 0.37727464 0.38390262]]

 [[0.30200197 0.19513099 0.73631465]
  [0.92730206 0.68423275 0.42420571]
  [0.56635137 0.21497922 0.15703111]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [117]:
# Crear una matriz de 10 filas y 10 columnas
matriz = np.random.random((10, 10))

# Encontrar el valor mínimo
valor_minimo = matriz.min()

# Encontrar el valor máximo
valor_maximo = matriz.max()

print("Matriz:")
print(matriz)

print("Valor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

Matriz:
[[0.83581416 0.84505523 0.64368206 0.13424074 0.17672245 0.31886793
  0.9560486  0.22658518 0.89068826 0.93259473]
 [0.08510503 0.8113844  0.99443124 0.35272314 0.4840603  0.7421301
  0.37277431 0.0351575  0.15266311 0.32169685]
 [0.11750783 0.35968487 0.69759835 0.79224132 0.44617012 0.97074786
  0.51071352 0.48609896 0.05341272 0.24633288]
 [0.75592653 0.62749674 0.74802555 0.98769629 0.58993676 0.50637582
  0.21728289 0.57407349 0.78191488 0.83021552]
 [0.24107067 0.85496366 0.14261648 0.759887   0.93354342 0.71597823
  0.12805138 0.122318   0.60531038 0.98359658]
 [0.90447715 0.26103618 0.59673101 0.3340151  0.44550347 0.6449255
  0.34167404 0.84414    0.62830878 0.20018449]
 [0.38096354 0.52351223 0.67537613 0.28125893 0.7534345  0.70156022
  0.09602485 0.10198849 0.34397154 0.82000126]
 [0.92464576 0.75815227 0.87908158 0.85414501 0.17044836 0.58471732
  0.35069356 0.73865133 0.02897083 0.17296183]
 [0.13388894 0.9802295  0.93205954 0.70622076 0.93604342 0.73718604
  0.38

### 14. Create a random vector of size 30 and find the mean value

In [118]:
# Crear un vector con 30 valores aleatorios
vector = np.random.random(30)

# Calcular el promedio de sus valores
promedio = vector.mean()

print("Vector:")
print(vector)

print("Promedio:", promedio)

Vector:
[0.10917502 0.70361658 0.78450887 0.85904413 0.70221941 0.9010161
 0.76475656 0.75957701 0.07690665 0.09912849 0.2779539  0.15247297
 0.10991839 0.47912258 0.32346691 0.69717284 0.42581536 0.84637056
 0.46792695 0.86147869 0.06098851 0.14581066 0.64853801 0.38685472
 0.46231367 0.10714739 0.17766136 0.57485733 0.55096856 0.46891072]
Promedio: 0.46618996341964464


### 15. Create a 2d array with 1 on the border and 0 inside

In [119]:
# Crear una matriz de 5x5 llena de unos
matriz = np.ones((5, 5))

# Cambiar los elementos internos por ceros
matriz[1:-1, 1:-1] = 0

print(matriz)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [120]:
# Crear una matriz existente de 3x3
matriz = np.ones((3, 3))

print("Matriz original:")
print(matriz)

# Agregar un borde de tamaño 1 lleno de ceros
matriz_con_borde = np.pad(
    matriz,
    pad_width=1,
    mode="constant",
    constant_values=0
)

print("Matriz con borde:")
print(matriz_con_borde)

Matriz original:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriz con borde:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression?

In [121]:
# Representa un valor numérico indefinido

print("1.", 0 * np.nan)
print("2.", np.nan == np.nan)
print("3.", np.inf > np.nan)
print("4.", np.nan - np.nan)
print("5.", np.nan in set([np.nan]))
print("6.", 0.3 == 3 * 0.1)

1. nan
2. False
3. False
4. nan
5. True
6. False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [122]:
# Crear los valores que irán debajo de la diagonal principal
valores = np.array([1, 2, 3, 4])

# k=-1 coloca los valores una posición debajo de la diagonal principal
matriz = np.diag(valores, k=-1)

print(matriz)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [123]:
# Crear una matriz de 8x8 llena de ceros
tablero = np.zeros((8, 8), dtype=int)

# Colocar unos en posiciones alternadas de las filas pares
tablero[0::2, 1::2] = 1

# Colocar unos en posiciones alternadas de las filas impares
tablero[1::2, 0::2] = 1

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [125]:
# Definir la forma del arreglo
forma = (6, 7, 8)

# Los índices comienzan desde cero
# Por eso, el elemento número 100 corresponde a la posición 99
indice = np.unravel_index(99, forma)

print("Índice del elemento número 100:", indice)

Índice del elemento número 100: (np.int64(1), np.int64(5), np.int64(3))


### 21. Create a checkerboard 8x8 matrix using the tile function

In [126]:
# Crear un patrón básico de 2x2
patron = np.array([
    [0, 1],
    [1, 0]
])

# Repetir el patrón 4 veces en filas y 4 veces en columnas
tablero = np.tile(patron, (4, 4))

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix

In [127]:
# Crear una matriz aleatoria de 5x5
matriz = np.random.random((5, 5))

# Obtener el valor mínimo y máximo
minimo = matriz.min()
maximo = matriz.max()

# Normalizar la matriz entre 0 y 1
matriz_normalizada = (matriz - minimo) / (maximo - minimo)

print("Matriz original:")
print(matriz)

print("\nMatriz normalizada:")
print(matriz_normalizada)

Matriz original:
[[0.84361359 0.29882568 0.63316204 0.40657968 0.47604698]
 [0.86989094 0.37762823 0.48361506 0.14038611 0.07544315]
 [0.68808941 0.82006319 0.61670132 0.89608079 0.63052799]
 [0.80032326 0.36206458 0.02771319 0.92933013 0.56270629]
 [0.85098844 0.42914757 0.71083112 0.86536558 0.42707521]]

Matriz normalizada:
[[0.90493021 0.30069588 0.6715145  0.42020783 0.49725529]
 [0.9340749  0.38809724 0.50564919 0.12496762 0.05293818]
 [0.73243547 0.87881003 0.65325762 0.96312254 0.66859303]
 [0.8569161  0.3708353  0.         1.         0.59337073]
 [0.91310979 0.44523829 0.75765872 0.92905574 0.44293979]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [128]:
# Crear un tipo de dato personalizado para colores RGBA
color_rgba = np.dtype([
    ("R", np.uint8),
    ("G", np.uint8),
    ("B", np.uint8),
    ("A", np.uint8)
])

# Crear un color de ejemplo
color = np.array((255, 100, 50, 255), dtype=color_rgba)

print(color)
print("Rojo:", color["R"])
print("Verde:", color["G"])
print("Azul:", color["B"])
print("Transparencia:", color["A"])

(255, 100, 50, 255)
Rojo: 255
Verde: 100
Azul: 50
Transparencia: 255


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [129]:
# Crear una matriz de 5 filas y 3 columnas
matriz_a = np.random.randint(1, 10, (5, 3))

# Crear una matriz de 3 filas y 2 columnas
matriz_b = np.random.randint(1, 10, (3, 2))

# Realizar el producto matricial
resultado = matriz_a @ matriz_b

print("Matriz A:")
print(matriz_a)

print("\nMatriz B:")
print(matriz_b)

print("\nResultado de la multiplicación:")
print(resultado)

Matriz A:
[[8 4 5]
 [8 1 7]
 [4 2 6]
 [2 1 4]
 [5 1 9]]

Matriz B:
[[4 9]
 [6 3]
 [8 7]]

Resultado de la multiplicación:
[[ 96 119]
 [ 94 124]
 [ 76  84]
 [ 46  49]
 [ 98 111]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [130]:
# Crear un arreglo de una dimensión
vector = np.arange(11)

print("Vector original:")
print(vector)

# Crear una condición para seleccionar valores entre 3 y 8
condicion = (vector > 3) & (vector < 8)

# Negar los valores seleccionados dentro del mismo vector
vector[condicion] *= -1

print("\nVector modificado:")
print(vector)

Vector original:
[ 0  1  2  3  4  5  6  7  8  9 10]

Vector modificado:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
